# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

before_install:
- openssl aes-256-cbc -K $encrypted_ff3d0b913aa4_key -iv $encrypted_ff3d0b913aa4_iv
  -in lab-devops-cloud-314617-2cc3fc945047.json.enc -out ../lab-devops-cloud-314617-2cc3fc945047.json
  -d
# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install flask

# Defini o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - python -m unittest -v test

# Definir o Deploy no Heroku
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true 
  app: devopslab-vargas
  on:
      branch: main

- provider: gae
    keyfile: ../lab-devops-cloud-e2c2da9aee66.json
    project: lab-devops-cloud-314617
    on:
      branch: main

